vim.o.background = "light"
vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "monstera"

local palette = {
  bg = "#e1ede1",
  bg_alt = "#bfcfba",
  bg_float = "#f3f3f3",
  explorer_bg = "#c0cfbc",
  fg = "#1a3020",
  muted = "#777777",
  subtle = "#aaaaaa",
  border = "#bfcfba",
  selection = "#749c8c",
  cursor = "#4a6020",
  green = "#448c27",
  green_dark = "#4a6020",
  olive = "#7d8b01",
  yellow = "#968200",
  orange = "#ab6526",
  red = "#aa3731",
  red_bright = "#c72e0f",
  blue = "#4b83cd",
  blue_bright = "#1a85ff",
  cyan = "#237893",
  purple = "#7a3e9d",
  bracket = "#7ebd80",
}

local groups = {
  Normal = { fg = palette.fg, bg = palette.bg },
  NormalNC = { fg = palette.fg, bg = palette.bg },
  NormalFloat = { fg = palette.fg, bg = palette.bg_float },
  FloatBorder = { fg = palette.green_dark, bg = palette.bg_float },
  FloatTitle = { fg = palette.green_dark, bg = palette.bg_float, bold = true },
  Cursor = { fg = palette.bg, bg = palette.cursor },
  CursorLine = { bg = "#d6e4d4" },
  CursorColumn = { bg = "#d6e4d4" },
  ColorColumn = { bg = "#d6e4d4" },
  LineNr = { fg = palette.cyan, bg = palette.bg },
  CursorLineNr = { fg = palette.green_dark, bg = "#d6e4d4", bold = true },
  SignColumn = { fg = palette.fg, bg = palette.bg },
  FoldColumn = { fg = palette.muted, bg = palette.bg },
  Folded = { fg = palette.muted, bg = palette.bg_alt },
  EndOfBuffer = { fg = palette.bg_alt, bg = palette.bg },
  NonText = { fg = palette.subtle },
  Whitespace = { fg = "#9bac98" },
  SpecialKey = { fg = palette.cyan },
  Visual = { fg = palette.fg, bg = palette.selection },
  VisualNOS = { fg = palette.fg, bg = palette.selection },
  Search = { fg = palette.fg, bg = "#b2bd7e" },
  IncSearch = { fg = palette.bg, bg = palette.orange },
  CurSearch = { fg = palette.bg, bg = palette.orange },
  MatchParen = { fg = palette.green_dark, bg = "#c9ddc5", bold = true },
  WinSeparator = { fg = palette.border, bg = palette.bg },
  VertSplit = { fg = palette.border, bg = palette.bg },
  StatusLine = { fg = palette.fg, bg = palette.bg_alt },
  StatusLineNC = { fg = palette.muted, bg = palette.bg_alt },
  TabLine = { fg = palette.muted, bg = palette.bg_alt },
  TabLineFill = { fg = palette.muted, bg = palette.bg_alt },
  TabLineSel = { fg = palette.fg, bg = palette.bg, bold = true },
  Pmenu = { fg = palette.fg, bg = palette.bg_float },
  PmenuSel = { fg = palette.bg, bg = palette.green_dark },
  PmenuSbar = { bg = palette.bg_alt },
  PmenuThumb = { bg = palette.green_dark },
  WildMenu = { fg = palette.bg, bg = palette.green_dark },
  Question = { fg = palette.green_dark },
  MoreMsg = { fg = palette.green_dark },
  ModeMsg = { fg = palette.green_dark },
  Directory = { fg = palette.blue },
  Title = { fg = palette.green_dark, bold = true },

  MiniFilesNormal = { fg = palette.fg, bg = palette.explorer_bg },
  MiniFilesBorder = { fg = palette.green_dark, bg = palette.explorer_bg },
  MiniFilesBorderModified = { fg = palette.orange, bg = palette.explorer_bg },
  MiniFilesCursorLine = { fg = palette.fg, bg = "#d6e4d4" },
  MiniFilesDirectory = { fg = palette.green_dark, bg = palette.explorer_bg, bold = true },
  MiniFilesFile = { fg = palette.fg, bg = palette.explorer_bg },
  MiniFilesTitle = { fg = palette.fg, bg = palette.explorer_bg },
  MiniFilesTitleFocused = { fg = palette.green_dark, bg = palette.explorer_bg, bold = true },
  SnacksPickerBox = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksPickerBoxBorder = { fg = palette.green_dark, bg = palette.explorer_bg },
  SnacksPickerBoxCursorLine = { fg = palette.fg, bg = "#d6e4d4" },
  SnacksPickerList = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksPickerListBorder = { fg = palette.green_dark, bg = palette.explorer_bg },
  SnacksPickerListCursorLine = { fg = palette.fg, bg = "#d6e4d4" },
  SnacksPickerListTitle = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksPickerInput = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksPickerInputBorder = { fg = palette.green_dark, bg = palette.explorer_bg },
  SnacksPickerInputCursorLine = { fg = palette.fg, bg = "#d6e4d4" },
  SnacksPickerInputTitle = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksPickerDirectory = { fg = palette.green_dark, bg = palette.explorer_bg, bold = true },
  SnacksPickerFile = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksPickerDir = { fg = palette.muted, bg = palette.explorer_bg },
  SnacksPickerTree = { fg = palette.green_dark, bg = palette.explorer_bg },
  SnacksPickerPathHidden = { fg = palette.muted, bg = palette.explorer_bg },
  SnacksPickerPathIgnored = { fg = palette.muted, bg = palette.explorer_bg },
  SnacksNormal = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksNormalNC = { fg = palette.fg, bg = palette.explorer_bg },
  SnacksWinSeparator = { fg = palette.green_dark, bg = palette.explorer_bg },
  NeoTreeNormal = { fg = palette.fg, bg = palette.explorer_bg },
  NeoTreeNormalNC = { fg = palette.fg, bg = palette.explorer_bg },
  NeoTreeEndOfBuffer = { fg = palette.explorer_bg, bg = palette.explorer_bg },
  NeoTreeWinSeparator = { fg = palette.green_dark, bg = palette.explorer_bg },
  NeoTreeDirectoryName = { fg = palette.green_dark, bg = palette.explorer_bg, bold = true },
  NeoTreeFileName = { fg = palette.fg, bg = palette.explorer_bg },
  NvimTreeNormal = { fg = palette.fg, bg = palette.explorer_bg },
  NvimTreeNormalNC = { fg = palette.fg, bg = palette.explorer_bg },
  NvimTreeEndOfBuffer = { fg = palette.explorer_bg, bg = palette.explorer_bg },
  NvimTreeFolderName = { fg = palette.green_dark, bg = palette.explorer_bg, bold = true },
  NvimTreeOpenedFolderName = { fg = palette.green_dark, bg = palette.explorer_bg, bold = true },

  Comment = { fg = palette.muted, italic = true },
  Constant = { fg = palette.orange },
  String = { fg = palette.green },
  Character = { fg = palette.green },
  Number = { fg = palette.orange },
  Boolean = { fg = palette.orange },
  Float = { fg = palette.orange },
  Identifier = { fg = palette.fg },
  Function = { fg = palette.green_dark },
  Statement = { fg = palette.olive },
  Conditional = { fg = palette.olive },
  Repeat = { fg = palette.olive },
  Label = { fg = palette.olive },
  Operator = { fg = palette.muted },
  Keyword = { fg = palette.olive },
  Exception = { fg = palette.yellow },
  PreProc = { fg = palette.purple },
  Include = { fg = palette.purple },
  Define = { fg = palette.purple },
  Macro = { fg = palette.purple },
  PreCondit = { fg = palette.purple },
  Type = { fg = palette.orange },
  StorageClass = { fg = palette.olive },
  Structure = { fg = palette.orange },
  Typedef = { fg = palette.orange },
  Special = { fg = palette.blue },
  SpecialChar = { fg = palette.blue },
  Tag = { fg = palette.green_dark },
  Delimiter = { fg = palette.muted },
  Debug = { fg = palette.red },
  Underlined = { fg = palette.blue, underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = palette.red_bright, bg = palette.bg },
  Todo = { fg = palette.bg, bg = palette.green_dark, bold = true },

  DiffAdd = { fg = palette.green_dark, bg = "#d4e8d2" },
  DiffChange = { fg = palette.yellow, bg = "#e3e7c9" },
  DiffDelete = { fg = palette.red_bright, bg = "#efd4cf" },
  DiffText = { fg = palette.orange, bg = "#d8dcb8", bold = true },

  DiagnosticError = { fg = palette.red_bright },
  DiagnosticWarn = { fg = palette.orange },
  DiagnosticInfo = { fg = palette.blue },
  DiagnosticHint = { fg = palette.green_dark },
  DiagnosticOk = { fg = palette.green },
  DiagnosticUnnecessary = {},
  DiagnosticUnderlineError = { undercurl = true, sp = palette.red_bright },
  DiagnosticUnderlineWarn = { undercurl = true, sp = palette.orange },
  DiagnosticUnderlineInfo = { undercurl = true, sp = palette.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = palette.green_dark },
  DiagnosticVirtualTextError = { fg = palette.red_bright, bg = "#efd4cf" },
  DiagnosticVirtualTextWarn = { fg = palette.orange, bg = "#e8dfc8" },
  DiagnosticVirtualTextInfo = { fg = palette.blue, bg = "#d7e3ec" },
  DiagnosticVirtualTextHint = { fg = palette.green_dark, bg = "#d4e8d2" },

  GitSignsAdd = { fg = palette.green },
  GitSignsChange = { fg = palette.orange },
  GitSignsDelete = { fg = palette.red_bright },
  SatelliteCursor = { fg = palette.green_dark },
  SatelliteSearch = { fg = palette.orange },
  SatelliteSearchCurrent = { fg = palette.bg, bg = palette.orange, bold = true },
  SatelliteDiagnosticError = { fg = palette.red_bright },
  SatelliteDiagnosticWarn = { fg = palette.orange },
  SatelliteDiagnosticInfo = { fg = palette.blue },
  SatelliteDiagnosticHint = { fg = palette.green_dark },
  SatelliteGitSignsAdd = { fg = palette.green },
  SatelliteGitSignsChange = { fg = palette.orange },
  SatelliteGitSignsDelete = { fg = palette.red_bright },
  SatelliteMark = { fg = palette.purple },
  SatelliteQuickfix = { fg = palette.yellow },
  Added = { fg = palette.green },
  Changed = { fg = palette.orange },
  Removed = { fg = palette.red_bright },
}

local treesitter_groups = {
  ["@attribute"] = { fg = palette.orange },
  ["@boolean"] = { fg = palette.orange },
  ["@character"] = { fg = palette.green },
  ["@comment"] = { fg = palette.muted, italic = true },
  ["@conditional"] = { fg = palette.olive },
  ["@constant"] = { fg = palette.orange },
  ["@constant.builtin"] = { fg = palette.orange },
  ["@constructor"] = { fg = palette.orange },
  ["@function"] = { fg = palette.green_dark },
  ["@function.builtin"] = { fg = palette.green_dark },
  ["@function.call"] = { fg = palette.green_dark },
  ["@keyword"] = { fg = palette.olive },
  ["@keyword.function"] = { fg = palette.olive },
  ["@keyword.operator"] = { fg = palette.muted },
  ["@label"] = { fg = palette.olive },
  ["@markup.heading"] = { fg = palette.red, bold = true },
  ["@markup.link"] = { fg = palette.blue, underline = true },
  ["@markup.list"] = { fg = palette.blue },
  ["@markup.raw"] = { fg = palette.orange },
  ["@number"] = { fg = palette.orange },
  ["@operator"] = { fg = palette.muted },
  ["@property"] = { fg = palette.fg },
  ["@punctuation"] = { fg = palette.muted },
  ["@punctuation.bracket"] = { fg = palette.bracket },
  ["@repeat"] = { fg = palette.olive },
  ["@string"] = { fg = palette.green },
  ["@string.escape"] = { fg = palette.muted },
  ["@string.regexp"] = { fg = palette.blue },
  ["@tag"] = { fg = palette.green_dark },
  ["@tag.attribute"] = { fg = palette.orange },
  ["@tag.delimiter"] = { fg = palette.muted },
  ["@type"] = { fg = palette.orange },
  ["@variable"] = { fg = palette.fg },
  ["@variable.builtin"] = { fg = palette.purple },
  ["@variable.parameter"] = { fg = palette.fg },
  ["@lsp.mod.unnecessary"] = {},
  ["@lsp.mod.unnecessary.typescript"] = {},
  ["@lsp.mod.unnecessary.typescriptreact"] = {},
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

for group, opts in pairs(treesitter_groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

vim.g.terminal_color_0 = palette.fg
vim.g.terminal_color_1 = palette.red
vim.g.terminal_color_2 = palette.green
vim.g.terminal_color_3 = palette.yellow
vim.g.terminal_color_4 = palette.blue
vim.g.terminal_color_5 = palette.purple
vim.g.terminal_color_6 = palette.cyan
vim.g.terminal_color_7 = palette.bg_alt
vim.g.terminal_color_8 = palette.muted
vim.g.terminal_color_9 = palette.red_bright
vim.g.terminal_color_10 = palette.green_dark
vim.g.terminal_color_11 = palette.orange
vim.g.terminal_color_12 = palette.blue_bright
vim.g.terminal_color_13 = "#bd9d7e"
vim.g.terminal_color_14 = palette.bracket
vim.g.terminal_color_15 = palette.bg_float
